spring:
  application:
    name: todowithcouchbase
  config:
    import: optional:file:.env[.properties]
  couchbase:
    connection-string: couchbase://${COUCHBASE_HOST:127.0.0.1}
    username: ${COUCHBASE_USERNAME:Administrator}
    password: ${COUCHBASE_PASSWORD:123456}
    bucket: ${COUCHBASE_BUCKET:todo_list}
    enable-tls: false
    enable-dns-srv: false
    auto-index-creation: true
    scopes:
      user-scope: user-scope
      task-scope: task-scope
      invalid-token-scope: invalid-token-scope
      log-scope: log-scope
    collections:
      user-collection: user-collection
      task-collection: task-collection
      invalid-token-collection: invalid-token-collection
      log-collection: log-collection


server:
  shutdown: graceful
  port: 2323

# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true