spring:
  application:
    name: todowithcouchbase
  config:
    import: optional:file:.env[.properties]
  couchbase:
    connection-string: couchbase://${COUCHBASE_HOST:127.0.0.1}
    username: ${COUCHBASE_USERNAME:Administrator}
    password: ${COUCHBASE_PASSWORD:123456}
    bucket: ${COUCHBASE_BUCKET:todo_list}
    scopes:
      user-scope: user
      task-scope: task
      invalid-token-scope : invalid-token
    collections:
      user-scope: user
      task-scope: task
      invalid-token-scope: invalid-token


  data:
    couchbase:
      auto-index: true

server:
  shutdown: graceful
  port: 2323