spring:
  application:
    name: todowithcouchbase
  config:
    import: optional:file:.env[.properties]
  couchbase:
    connection-string: couchbase://${COUCHBASE_HOST:127.0.0.1}
    username: ${COUCHBASE_USERNAME:Administrator}
    password: ${COUCHBASE_PASSWORD:123456}
    bucket: ${COUCHBASE_BUCKET:todo_list}
    scopes:
      user-scope: user-scope
      task-scope: task-scope
      invalid-token-scope : invalid-token-scope
      log-scope: log-scope
    collections:
      user-collection: user-collection
      task-collection: task-collection
      invalid-token-collection: invalid-token-collection
      log-collection : log-collection


  data:
    couchbase:
      auto-index: true

server:
  shutdown: graceful
  port: 2323