apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase
spec:
  selector:
    matchLabels:
      app: couchbase
  serviceName: couchbase
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:latest
          ports:
            - containerPort: 8091
            - containerPort: 11210
          env:
            - name: COUCHBASE_ADMINISTRATOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase-secret
                  key: username
            - name: COUCHBASE_ADMINISTRATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase-secret
                  key: password
            - name: COUCHBASE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: COUCHBASE_BUCKET
          volumeMounts:
            - name: couchbase-storage
              mountPath: /opt/couchbase/var
      volumes:
        - name: couchbase-storage
          persistentVolumeClaim:
            claimName: couchbase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  selector:
    app: couchbase
  ports:
    - name: admin-port
      protocol: TCP
      port: 8091
      targetPort: 8091
    - name: data-port
      protocol: TCP
      port: 11210
      targetPort: 11210
  type: NodePort
