apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchbase-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/couchbase
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
